In [2]:
import numpy as np
from scipy import stats
import pandas as pd

In [3]:
# 성적의 평균 구하기
x = [70, 60, 80, 60, 50]
print(np.sum(x)/len(x))
print(np.mean(x))
print(np.array(x).mean())
print(pd.Series(x).mean())

64.0
64.0
64.0
64.0

In [5]:
x = np.array([60, 40])
print(round(len(x) / (1/60 + 1/40),1))
print(round(len(x) / np.sum(1/x),1))
print(round(stats.hmean(x),1))

48.0
48.0
48.0

# 상황: 두 생산 라인이 동일한 수의 제품(작업량)을 생산하지만, 
# 각 라인의 처리 속도가 다를 때 평균 처리 속도를 계산하기

# 라인 A: 60개/시간, 라인 B: 30개/시간  → 동일 작업량(120개 제품 생산) 처리 시 평균 처리속도

In [6]:
x = np.array([60,30])
print(round(len(x) / (1/60 + 1/30),1))
print(round(len(x) / np.sum(1/x),1))
print(round(stats.hmean(x),1))

40.0
40.0
40.0

절사 평균에

In [9]:
np.random.seed(0)
income = np.random.normal(3000000, 500000, 100) 
print(round(np.mean(income), 2))
income = np.append(income, 10**8) 
print(round(np.mean(income), 2))

3029904.01
3990003.97

In [ ]:
x = np.random.choice(['A', 'B', 'C'], 2000) # A, B, C라는 요소로 데이터 1000개 만들기
print(x[:20])
print(len(x))

#파이선 모듈
from collections import Counter
counter = Counter(x)
mode_value, mode_count = counter.most_common(1)[0]  # 최빈값과 빈도수 추출


print("최빈값:", mode_value)
print("최빈값의 빈도수:", mode_count)

['A' 'C' 'B' 'C' 'C' 'A' 'B' 'A' 'A' 'B' 'A' 'A' 'C' 'A' 'A' 'A' 'C' 'B'
 'C' 'A']
2000
최빈값: B
최빈값의 빈도수: 699

In [75]:
income = np.append(income, 10**8) 
print(round(np.mean(income), 2))

#파이선 모듈
from collections import Counter
counter = Counter(income)
mode_value, mode_count = counter.most_common(1)[0]  # 최빈값과 빈도수 추출


print("최빈값:", mode_value)
print("최빈값의 빈도수:", mode_count)

33124071.73
최빈값: 100000000.0
최빈값의 빈도수: 45

In [78]:
import numpy as np
import pandas as pd

x1 = np.array([1,2,3,4,5])
x2 = x1*10

z1 = (x1 - x1.mean()) / x1.std()
z2 = (x2 -x2.mean()) / x2.std()

print(z1)
print(z2)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

In [79]:
#Min-max Scaling
z1 = (x1 - x1.min()) / (x1.max() - x1.min())
z2 = (x2 - x2.min()) / (x2.max() - x2.min())

print(z1)
print(z2)

[0.   0.25 0.5  0.75 1.  ]
[0.   0.25 0.5  0.75 1.  ]

In [91]:
# sklearn을 이용한 스케일링을 위한 데이터 준비
X = pd.DataFrame({"X1":[1, 2, 3, 4, 5],
    "X2": [10, 20, 30, 40, 50]})


from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() #인스턴스화
Z = scaler.fit_transform(X) #fit.transfom = ndaaray


pd.DataFrame(Z, columns=['X1','X2'])

     X1    X2
0  0.00  0.00
1  0.25  0.25
2  0.50  0.50
3  0.75  0.75
4  1.00  1.00

In [92]:
# 표준 정규분포에 따라서 데이터의 수준을 맞춤
# 표준 정규분포 : 
from sklearn.preprocessing import StandardScaler
ss_scaler = StandardScaler() # 인스턴스화
Z = ss_scaler.fit_transform(X) # fit_transform => ndarray
pd.DataFrame(Z, columns=['X1', 'X2'])

         X1        X2
0 -1.414214 -1.414214
1 -0.707107 -0.707107
2  0.000000  0.000000
3  0.707107  0.707107
4  1.414214  1.414214